(function () {
  'use strict';
  const { dateKey, addDays, startOfWeek, uid, repository } = window.PlannerData;
  const $ = (selector) => document.querySelector(selector), $$ = (selector) => [...document.querySelectorAll(selector)];
  const escapeHtml = (value) => { const node = document.createElement('span'); node.textContent = value; return node.innerHTML; };
  const formatDay = (date) => new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric', weekday: 'long' }).format(date);
  const parseDate = (key) => new Date(`${key}T12:00:00`);
  let state = repository.load(), selectedDate = new Date(), view = 'day', saveTimer;
  function save(message = '저장됨') { repository.save(state); clearTimeout(saveTimer); $('#saveState').textContent = message; saveTimer = setTimeout(() => { $('#saveState').textContent = '자동 저장됩니다.'; }, 1100); }
  function goals() { return state.goals.filter((goal) => goal.active); }
  function goalName(id) { return state.goals.find((goal) => goal.id === id)?.title || '목표 미지정'; }
  function tasksFor(key) { return state.plans.tasks.filter((task) => task.date === key).sort((a, b) => a.priority.localeCompare(b.priority) || a.order - b.order); }
  function renderHeader() {
    const key = dateKey(selectedDate);
    if (view === 'day') { $('#dateKicker').textContent = 'DAILY COMPASS'; $('#dateTitle').textContent = formatDay(selectedDate); $('#dateSubtitle').textContent = '중요한 일을 먼저 정하고, 시간을 약속하세요.'; }
    else { const start = startOfWeek(selectedDate), end = addDays(start, 6); $('#dateKicker').textContent = 'WEEKLY COMPASS'; $('#dateTitle').textContent = `${start.getMonth() + 1}.${start.getDate()} — ${end.getMonth() + 1}.${end.getDate()}`; $('#dateSubtitle').textContent = '한 주의 균형을 살피고, 중요한 결과에 공간을 만드세요.'; }
    $('#todayButton').classList.toggle('is-today', key === dateKey());
  }
  function renderGoals() { $('#goalList').innerHTML = goals().map((goal) => `<div class="goal-chip"><span>${escapeHtml(goal.title)}</span><button data-delete-goal="${goal.id}" aria-label="목표 삭제">×</button></div>`).join(''); $('#taskGoal').innerHTML = ['<option value="">목표 미지정</option>', ...goals().map((goal) => `<option value="${goal.id}">${escapeHtml(goal.title)}</option>`)].join(''); }
  function renderTasks() { const tasks = tasksFor(dateKey(selectedDate)); $('#taskEmpty').hidden = tasks.length > 0; $('#taskList').innerHTML = tasks.map((task) => `<article class="task-item ${task.completed ? 'completed' : ''}"><button class="task-check" data-toggle-task="${task.id}" aria-pressed="${task.completed}" aria-label="완료 전환">${task.completed ? '✓' : ''}</button><span class="priority-mark priority-${task.priority}">${task.priority}${task.order}</span><div class="task-copy"><strong>${escapeHtml(task.title)}</strong><small>${escapeHtml(goalName(task.goalId))} · ${task.duration}분</small></div><button class="item-delete" data-delete-task="${task.id}" aria-label="할 일 삭제">×</button></article>`).join(''); }
  function renderTimeline() { const blocks = state.plans.timeBlocks.filter((block) => block.date === dateKey(selectedDate)).sort((a, b) => a.start.localeCompare(b.start)); $('#timeline').innerHTML = blocks.length ? blocks.map((block) => `<article class="time-block ${block.tone}"><span class="time">${block.start}</span><strong>${escapeHtml(block.title)}</strong><small>${block.start} — ${block.end}</small><button class="item-delete" data-delete-block="${block.id}" aria-label="시간 블록 삭제">×</button></article>`).join('') : '<div class="timeline-empty">아직 확보한 시간이 없습니다.<br>중요한 일을 달력보다 먼저 약속해 보세요.</div>'; }
  function renderNotes() { const note = state.plans.dailyNotes[dateKey(selectedDate)] || {}; $('#dailyFocus').value = note.focus || ''; $('#dailyReview').value = note.review || ''; const weekly = state.plans.weeklyNotes[dateKey(startOfWeek(selectedDate))] || {}; $('#weeklyOutcome').value = weekly.outcome || ''; $('#weeklyAvoid').value = weekly.avoid || ''; }
  function renderWeek() { const start = startOfWeek(selectedDate), names = ['월', '화', '수', '목', '금', '토', '일']; $('#weekBoard').innerHTML = names.map((name, index) => { const day = addDays(start, index), key = dateKey(day), tasks = tasksFor(key), done = tasks.filter((task) => task.completed).length; return `<article class="week-day ${key === dateKey() ? 'today' : ''} ${key === dateKey(selectedDate) ? 'selected' : ''}" data-week-date="${key}"><header><span class="week-day-name">${name}요일</span><span class="week-date">${day.getDate()}</span></header>${tasks.map((task) => `<div class="week-task ${task.priority} ${task.completed ? 'done' : ''}">${escapeHtml(task.title)}</div>`).join('') || '<div class="week-task C">여백을 남겨두세요</div>'}<span class="week-count">${done} / ${tasks.length} COMPLETE</span></article>`; }).join(''); }
  function render() { renderHeader(); renderGoals(); renderTasks(); renderTimeline(); renderNotes(); renderWeek(); $('#dayView').hidden = view !== 'day'; $('#weekView').hidden = view !== 'week'; $$('.view-tab').forEach((tab) => tab.classList.toggle('active', tab.dataset.view === view)); }
  $('#goalForm').addEventListener('submit', (event) => { event.preventDefault(); const title = $('#goalInput').value.trim(); if (!title) return; state.goals.push({ id: uid('goal'), title, area: '개인', active: true, sourceRef: null }); event.target.reset(); save(); renderGoals(); });
  $('#goalList').addEventListener('click', (event) => { const id = event.target.dataset.deleteGoal; if (!id) return; state.goals.find((goal) => goal.id === id).active = false; save(); render(); });
  $$('.view-tab').forEach((tab) => tab.addEventListener('click', () => { view = tab.dataset.view; render(); }));
  $('#prevDate').addEventListener('click', () => { selectedDate = addDays(selectedDate, view === 'week' ? -7 : -1); render(); }); $('#nextDate').addEventListener('click', () => { selectedDate = addDays(selectedDate, view === 'week' ? 7 : 1); render(); }); $('#todayButton').addEventListener('click', () => { selectedDate = new Date(); render(); });
  $$('[data-open]').forEach((button) => button.addEventListener('click', () => { const dialog = $(`#${button.dataset.open}`); dialog.querySelector('input[type=date]').value = dateKey(selectedDate); dialog.showModal(); }));
  $('#taskForm').addEventListener('submit', (event) => { if (event.submitter?.value === 'cancel') return; event.preventDefault(); const date = $('#taskDate').value, priority = $('#taskPriority').value; const order = Math.max(0, ...state.plans.tasks.filter((task) => task.date === date && task.priority === priority).map((task) => task.order)) + 1; state.plans.tasks.push({ id: uid('task'), date, title: $('#taskTitle').value.trim(), priority, order, goalId: $('#taskGoal').value || null, duration: +$('#taskDuration').value, completed: false, sourceRef: null }); save(); event.target.reset(); $('#taskDialog').close(); selectedDate = parseDate(date); render(); });
  $('#blockForm').addEventListener('submit', (event) => { if (event.submitter?.value === 'cancel') return; event.preventDefault(); const start = $('#blockStart').value, end = $('#blockEnd').value; if (end <= start) { alert('종료 시간은 시작 시간보다 늦어야 합니다.'); return; } const date = $('#blockDate').value; state.plans.timeBlocks.push({ id: uid('block'), date, start, end, title: $('#blockTitle').value.trim(), tone: $('#blockTone').value, taskId: null, sourceRef: null }); save(); event.target.reset(); $('#blockStart').value = '09:00'; $('#blockEnd').value = '10:00'; $('#blockDialog').close(); selectedDate = parseDate(date); render(); });
  $('#taskList').addEventListener('click', (event) => { const toggleId = event.target.dataset.toggleTask, deleteId = event.target.dataset.deleteTask; if (toggleId) { const task = state.plans.tasks.find((item) => item.id === toggleId); task.completed = !task.completed; } if (deleteId) state.plans.tasks = state.plans.tasks.filter((task) => task.id !== deleteId); if (toggleId || deleteId) { save(); renderTasks(); renderWeek(); } });
  $('#timeline').addEventListener('click', (event) => { const id = event.target.dataset.deleteBlock; if (!id) return; state.plans.timeBlocks = state.plans.timeBlocks.filter((block) => block.id !== id); save(); renderTimeline(); });
  $('#weekBoard').addEventListener('click', (event) => { const day = event.target.closest('[data-week-date]'); if (!day) return; selectedDate = parseDate(day.dataset.weekDate); view = 'day'; render(); });
  ['dailyFocus', 'dailyReview'].forEach((id) => $(`#${id}`).addEventListener('input', () => { const key = dateKey(selectedDate), note = state.plans.dailyNotes[key] || {}; note[id === 'dailyFocus' ? 'focus' : 'review'] = $(`#${id}`).value; state.plans.dailyNotes[key] = note; save('저장 중…'); }));
  ['weeklyOutcome', 'weeklyAvoid'].forEach((id) => $(`#${id}`).addEventListener('input', () => { const key = dateKey(startOfWeek(selectedDate)), note = state.plans.weeklyNotes[key] || {}; note[id === 'weeklyOutcome' ? 'outcome' : 'avoid'] = $(`#${id}`).value; state.plans.weeklyNotes[key] = note; save('저장 중…'); }));
  $('#resetPlanner').addEventListener('click', () => { if (!confirm('플래너 데이터를 처음 상태로 되돌릴까요?')) return; state = repository.reset(); repository.save(state); selectedDate = new Date(); view = 'day'; render(); });
  render();
})();
